[versions]
kotlin = "2.0.0"
jreleaser = "1.13.1"

[libraries]
jreleaser-plugin = { module = "org.jreleaser:org.jreleaser.gradle.plugin", version.ref = "jreleaser" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
